app: craft3-hgi6
ssh_url: craft3-hgi6@deploy.us1.frbit.com
git_remote: craft3-hgi6/master
before:
    code/up: {  }
after:
    code/down:
        - 'php craft migrate/all'
        - 'php craft project-config/apply'
