app: craft3-hgi6
ssh_url: craft3-hgi6@deploy.us1.frbit.com
ssh_path: null
git_remote: craft3-hgi6/master
before:
    code/up:
        - 'echo  "Script example: " $(git rev-parse HEAD)'
after:
    code/down:
        - 'php craft migrate/all'
