fieldLayouts:
  8ad8b5e6-10aa-419d-903f-d290fe265221:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 0b8b015c-6aea-4f7b-900b-96111adf5ac3
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: bb70288c-20b3-49d2-ab44-fdf80e138796
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3f3291a2-e7f3-4f28-b629-a8a782a329ca
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Application Account Links'
        sortOrder: 1
handle: eStore
hasTitleField: false
name: 'Request Account'
section: 6fbf9061-9641-4350-9e34-a974e674a2e9
sortOrder: 1
titleFormat: '{section.name|raw}'
