fieldLayouts:
  df2a16d7-354f-4714-aa91-761f0f09a527:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: a8bd193b-124c-4187-ac5c-c69ed84a7c3a
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'General Settings'
        sortOrder: 1
handle: profileAssessment
hasTitleField: false
name: 'Profile Assessment'
section: 3788ba9a-0fca-46b5-9c4c-73b9190133c0
sortOrder: 1
titleFormat: '{section.name|raw}'
