contentColumnType: string
fieldGroup: d1b2d3e0-caff-4265-8c15-310da7c6b14f
handle: externalLink
instructions: ''
name: 'External Link'
searchable: '1'
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
