enableVersioning: true
handle: accountApplications
name: 'Account Applications'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  d84c7a06-9ecd-42c4-b65c-ec087c3bba35:
    enabledByDefault: true
    hasUrls: true
    template: applications/_entry
    uriFormat: 'account-applications/{slug}'
type: channel
