enableVersioning: true
handle: banners
name: Banners
propagationMethod: all
siteSettings:
  d84c7a06-9ecd-42c4-b65c-ec087c3bba35:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
