enableVersioning: '1'
handle: locations
name: Locations
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  d84c7a06-9ecd-42c4-b65c-ec087c3bba35:
    enabledByDefault: '1'
    hasUrls: '1'
    template: locations
    uriFormat: locations
type: single
