enableVersioning: true
handle: scholarshipYearsRecipients
name: 'Scholarship Years & Recipients'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  d84c7a06-9ecd-42c4-b65c-ec087c3bba35:
    enabledByDefault: true
    hasUrls: true
    template: ''
    uriFormat: 'scholarship-years-recipients/{slug}'
type: channel
